=== yelircaasi/nebokrai-python-prototype/schemata/declaration/config-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Tracking JSON Schema",
    "description": "All configuration information, specifying algorithm parameters and all default values.",
    "type": "object",
    "properties": {
        "repr_width": {
            "type": "number"
        },
        "default_duration": {
            "type": "number"
        },
        "default_priority": {
            "type": "number"
        },
        "default_sleep_priority": {
            "type": "number"
        },
        "default_interval": {
            "type": "number"
        },
        "default_cluster_size": {
            "type": "number"
        },
        "default_order": {
            "type": "number"
        },
        "default_normaltime": {
            "type": "number"
        },
        "default_idealtime_factor": {
            "type": "number"
        },
        "default_mintime_factor": {
            "type": "number"
        },
        "default_maxtime_factor": {
            "type": "number"
        },
        "default_categories": {
            "type": "string"
        },
        "default_ismovable": {
            "type": "boolean"
        },
        "default_alignend": {
            "type": "boolean"
        },
        "default_day_start": {
            "type": "string",
            "pattern": "^[0-9]{1,2}:[0-9]{2}$"
        },
        "default_day_end": {
            "type": "string",
            "pattern": "^[0-9]{1,2}:[0-9]{2}$"
        },
        "default_empty_blocks": {
            "type": "string"
        },
        "default_project_dates_missing_offset": {
            "type": "number"
        },
        "default_project_dates_missing_hashmod": {
            "type": "number"
        },
        "default_schedule_weight_interval_min": {
            "type": "number"
        },
        "default_schedule_weight_interval_max": {
            "type": "number"
        },
        "default_sched_weight_transform_exp": {
            "type": "number"
        },
        "default_sleep_delta_min": {
            "type": "number"
        },
        "default_sleep_delta_max": {
            "type": "number"
        }
    }
}

=== yelircaasi/nebokrai-python-prototype/test/data/default/declaration/config.json
{
    "repr_width": 120,
    "default_duration": 30,
    "default_priority": 10,
    "default_sleep_priority": 70,
    "default_interval": 7,
    "default_cluster_size": 1,
    "default_order": 50.0,
    "default_normaltime": 30,
    "default_idealtime_factor": 1.5,
    "default_mintime_factor": 0.5,
    "default_maxtime_factor": 2.0,
    "default_categories": "wildcard",
    "default_ismovable": true,
    "default_alignend": false,
    "default_day_start": "05:00",
    "default_day_end": "22:00",
    "default_empty_blocks": "wildcard",
    "default_project_dates_missing_offset": 730,
    "default_project_dates_missing_hashmod": 30,
    "default_schedule_weight_interval_min": 1.0,
    "default_schedule_weight_interval_max": 1.1,
    "default_sched_weight_transform_exp": 2,
    "default_sleep_delta_min": 60,
    "default_sleep_delta_max": 60
}
